name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://npm.pkg.github.com
          scope: '@eatrejosm'

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Configure npm registry
        run: |
          echo "@eatrejosm:registry=https://npm.pkg.github.com" > build/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> build/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package
        run: npm publish
        working-directory: ./build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
